### ISSUE TITLE
Install deps when scaffolding

### ISSUE THREAD

**Issue by brillout** [brillout/reframe#8]
When we scaffold a new app, we should `npm install` so that the dependencies defined in the `package.json` of the scaffolded app are installed. (Such as the `react` dependency).

We could use cross-spawn (https://github.com/moxystudio/node-cross-spawn) to run `npm install`. `create-react-app` uses it as well.

Once we have done that the scaffolding will work 👍

**Comment by tdfranklin** [comment]
Ok, I have a question about this one... just want to make sure I implement correctly.  So after I require, basically I'll just need to run the following code after creating the file structure:

```javascript
const child = spawn('npm', ['install'], { stdio: 'inherit', cwd: currentDir });
```

So that should create the process and run npm install in the project directory, correct?  Should we also log some output with something like:

```javascript
child.stdout.on('data', data => {
  console.log(data);
}

child.on('close', code => {
  console.log(`process completed with code: ${code}`);
}
```

What are your thoughts?

**Comment by brillout** [comment]
Looks good. I didn't think everything through though. We'll see if it works out.

> Should we also log some output with something like:

Good question. I guess the bottom line is: Do we want to display npm's output or do we want to display a custom output? Why would we want to display npm's output? Maybe displaying npm's output only when something went wrong? What do you think?
